# Generated by Django 3.2.5 on 2022-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220312_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
