# Generated by Django 3.2.5 on 2022-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
