# Generated by Django 3.2.5 on 2022-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
