# Generated by Django 3.2.5 on 2022-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20220312_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbase',
            name='commission',
            field=models.IntegerField(default=5),
        ),
    ]
