# Generated by Django 3.2.5 on 2022-03-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='ticket_status',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='ticket_user',
        ),
    ]
