# Generated by Django 3.2.5 on 2022-03-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20220312_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_user',
            new_name='user',
        ),
    ]
